### ISSUE TITLE
[xfce]执行yum update报错

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#104]
![yum](https://user-images.githubusercontent.com/89007492/132326999-d0706f15-bb63-4275-9fb1-1cd873e0c175.jpg)

**Comment by GeassCore** [comment]
OS是什么？这个是之前yum 操作时强制中断导致数据库出错

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/132344627-52cd3a95-03fc-49cc-b5e7-73c9ec2eb064.png)

我这边运行是这样的

**Comment by GeassCore** [comment]
由于源中软件包版本和本机版本差异导致，使用正确源和镜像可以解决
