### ISSUE TITLE
[构建失败] gdbus-codegen-glibmm

### ISSUE THREAD

**Issue by xinminst** [isrc-cas/tarsier-oerv#106]
以下我分别使用osc在线和本地构建gdbus-codegen-glibmm的操作步骤

gdbus-codegen-glibmm包没有built binaries记录，应该从来没有构建成功过，查看gdbus-codegen-glibmm构建[失败日志](https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/gdbus-codegen-glibmm/standard_riscv64/riscv64)的报错：
```
[ 2979s] RPM build errors:
[ 2979s]     Directory not found: /home/abuild/rpmbuild/BUILDROOT/gdbus-codegen-glibmm-1.0.0-1.oe1.riscv64/usr/lib/python3.7/site-packages/gdbus_codegen.glibmm-2.99.0-py3.8.egg-info
[ 2979s]     File not found: /home/abuild/rpmbuild/BUILDROOT/gdbus-codegen-glibmm-1.0.0-1.oe1.riscv64/usr/lib/python3.7/site-packages/gdbus_codegen.glibmm-2.99.0-py3.8.egg-info/*
```
发现python3.7的文件夹下添加python3.8有关的文件导致报错（我觉得可能是写spec文件的笔误），故在gitee上fork相应包到[个人仓](https://gitee.com/xinminst/gdbus-codegen-glibmm)并修改spec文件中有关内容：
```
%files
%{_bindir}/gdbus-codegen-glibmm3
%dir %{python3_sitelib}/codegen_glibmm
%ifnarch riscv64
%dir %{python3_sitelib}/gdbus_codegen.glibmm-2.99.0-py3.8.egg-info
%else
%dir %{python3_sitelib}/gdbus_codegen.glibmm-2.99.0-py3.7.egg-info
%endif
%{python3_sitelib}/codegen_glibmm/*
%ifnarch riscv64
%{python3_sitelib}/gdbus_codegen.glibmm-2.99.0-py3.8.egg-info/*
%else
%{python3_sitelib}/gdbus_codegen.glibmm-2.99.0-py3.7.egg-info/*
%endif

```
在本地已经配置好osc环境的qemu下的openEuler riscv64中使用
```
osc branch openEuler:Mainline:RISC-V gdbus-codegen-glibmm
osc co home:xinminst:branches:openEuler:Mainline:RISC-V/gdbus-codegen-glibmm
```
拉取gdbus-codegen-glibmm到个人分支并将软件包配置信息下载到本地
在~/home:xinminst:branches:openEuler:Mainline:RISC-V/gdbus-codegen-glibmm下找到_service文件并修改为自己git仓修改后的版本：
```
<services>
    <service name="tar_scm">
      <param name="scm">git</param>
      <param name="url"> git@gitee.com:xinminst/gdbus-codegen-glibmm.git</param>
      <param name="exclude">.git</param>
      <param name="revision"> 5e30c03f5b7d85fe8a1e3f614c29addc3292317b</param>
    </service>
    <service name="extract_file">
        <param name="archive">*.tar</param>
        <param name="files">*/*</param>
    </service>
</services>

```
保存后上传service文件：
```
osc ci -m "update _service"
```
更新代码同步到本地：
```
osc up -S
```
重命名：
```
rm -f _service;for file in `ls`;do new_file=${file##*:};mv $file $new_file;done
```
添加重命名后的修改：
```
osc addremove *
```
更新文件：
```
osc up
```
上传：
```
osc ci -m "submit source" 
```
查看构建日志：
```
osc buildlog standard_riscv64 riscv64
```
构建成功结果截图：
![image](https://user-images.githubusercontent.com/87924498/132356897-45c19bfc-5d98-4638-896a-b3d0ab7182cf.png)

osc本地构建：
```
osc build
```
构建成功结果截图：
![gcg](https://user-images.githubusercontent.com/87924498/133430978-aadee4c2-9388-47b2-aafa-540223920f6f.PNG)

gitee上提交了[相关PR](https://gitee.com/openeuler-risc-v/gdbus-codegen-glibmm/pulls/1)

**Comment by laokz** [comment]
现成功构建链接：https://build.tarsier-infra.com/package/show/openEuler:22.03/gdbus-codegen-glibmm
