### ISSUE TITLE
[构建失败]pytest

### ISSUE THREAD

**Issue by MaximSuen** [isrc-cas/tarsier-oerv#107]
等待将`python3-pluggy`和`python-wcwidth`添加到依赖库

**Comment by MaximSuen** [comment]
把pluggy和wcwidth一起branch到个人仓后，开启use for build flag，构建成功：[链接](https://build.openeuler.org/package/show/home:maxim.suen:branches:openEuler:Mainline:RISC-V/pytest)

**Comment by laokz** [comment]
现成功构建链接：https://build.tarsier-infra.com/package/show/openEuler:22.03/pytest
