### ISSUE TITLE
[xfce]文件系统界面点击一个文件或文件夹，文件或文件夹的图标会和背景色融为一体，导致看不出图标

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#111]
image: openEuler-D1-xfce-docker.img.bz2

![icon](https://user-images.githubusercontent.com/89007492/132657115-e00f50bb-b18b-469a-b4b2-9e9e9603d62d.jpg)

**Comment by GeassCore** [comment]
同gtk问题
