### ISSUE TITLE
[obs]修复mozjs52

### ISSUE THREAD

**Issue by GeassCore** [isrc-cas/tarsier-oerv#118]
@liujiawei929

**Comment by lazyparser** [comment]
这个好像必要重要

**Comment by liujiawei929** [comment]
[mozjs52](https://build.openeuler.org/package/show/home:liujiawei:branches:home:liujiawei:branches:openEuler:Mainline:RISC-V/mozjs52)尽量仿照60修改,然而在52中没有third_party/rust/cc/src/lib.rs中的cc目录。我改了/third_party/rust/gcc/src/lib.rs中的gcc下的内容。。。。。

**Comment by lazyparser** [comment]
还有必要修么？

**Comment by laokz** [comment]
该包源码仓已关闭gitee.com/src-openeuler/mozjs52
