### ISSUE TITLE
[meta] spec中遇到valgrind或者valgrind-devel的处理

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#129]
参考文档：[unresolvable.json.txt](https://github.com/plctlab/openEuler-riscv/files/7168176/unresolvable.json.txt)

 1. 在上述json文档中搜索valgrind找到依赖valgrind 或者valgrind-devel包（ 一共16个）
 2. 将第一步找到的包：逐个修改spec文件：
 ```
spec中遇到valgrind或者valgrind-devel 改成下面的样子：
%ifarch %{valgrind_arches}
  BuildRequires: valgrind-devel
 %endif  
```
 
举例openmpi包：https://gitee.com/src-openeuler/openmpi/blob/master/openmpi.spec
```
。。。。
BuildRequires:      gcc-c++, gcc-gfortran
BuildRequires:      valgrind-devel, hwloc-devel, java-devel, libfabric-devel, papi-devel
BuildRequires:      libibverbs-devel >= 1.1.3, opensm-devel > 3.3.0
BuildRequires:      librdmacm-devel, rdma-core-devel, pmix-devel
BuildRequires:      hwloc-gui chrpath
BuildRequires:      perl-generators, perl(Getopt::Long)
BuildRequires:      python3-devel
%ifarch x86_64
BuildRequires:      infinipath-psm-devel, libpsm2-devel zlib-devel
%endif 

。。。。
```

修改为：
```
BuildRequires:      gcc-c++, gcc-gfortran
BuildRequires:      hwloc-devel, java-devel, libfabric-devel, papi-devel
BuildRequires:      libibverbs-devel >= 1.1.3, opensm-devel > 3.3.0
BuildRequires:      librdmacm-devel, rdma-core-devel, pmix-devel
BuildRequires:      hwloc-gui chrpath
BuildRequires:      perl-generators, perl(Getopt::Long)
BuildRequires:      python3-devel
%ifarch x86_64
BuildRequires:      infinipath-psm-devel, libpsm2-devel zlib-devel
%endif 

%ifarch %{valgrind_arches}
  BuildRequires: valgrind-devel
 %endif  

```

**Comment by xijing21** [comment]
补充一下：
上述16个包的源码目前openeuler-risc-v  源码仓应该是没有的，需要按照如下步骤：


第一步：在https://gitee.com/openeuler/RISC-V 修改 https://gitee.com/openeuler/RISC-V/blob/master/configuration/riscv_fork_list.yaml
按照格式，添加ck包（主要是name必须有，与src-openeuler一致）并提交PR，这样https://gitee.com/openeuler-risc-v 才会有源码包ck可以fork

第二步：从https://gitee.com/openeuler-risc-v  fork ck包到个人gitee下

第三步：在个人gitee、个人obs先修改测试，成功转第四步

第四步：提交PR到openeuler-risc-v

**Comment by MaximSuen** [comment]
|       包       | valgrind | valgrind-devel |                           构建结果                           |
| :------------: | :------: | :------------: | :----------------------------------------------------------: |
|      ceph      |          |       √        |                         unresolvable                         |
|    fabtests    |          |       √        |                         unresolvable                         |
|     fwupd      |    √     |       √        |                         unresolvable                         |
| gnome-software |          |       √        |                         unresolvable                         |
|       jq       |    √     |                | [succeeded](https://build.openeuler.org/package/live_build_log/home:maxim.suen:branches:openEuler:Mainline:RISC-V/jq/standard_riscv64/riscv64) |
|     libdap     |    √     |                |                         unresolvable                         |
|    libkate     |    √     |                |                                                              |
|   libsecret    |          |       √        |                                                              |
| libstoragemgmt |    √     |                |                                                              |
|      llvm      |          |       √        |                                                              |
|     mpich      |          |       √        |                                                              |
|    openmpi     |          |       √        |                                                              |
|   rapidjson    |    √     |                |                                                              |
|   rdma-core    |          |       √        |                                                              |
|      vdo       |          |       √        |                                                              |

**Comment by xijing21** [comment]
成功的提交PR，未成功的尝试看是否能够解决
