### ISSUE TITLE
[构建失败] kexec-tools

### ISSUE THREAD

**Issue by asdf1113** [isrc-cas/tarsier-oerv#142]
目前OBS端构建状态：不支持 riscv64 架构 [链接](https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/kexec-tools/standard_riscv64/riscv64)

`[ 1685s] configure: error: unsupported architecture riscv64
[ 1685s] error: Bad exit status from /var/tmp/rpm-tmp.xfGVLx (%build)`

**Comment by asdf1113** [comment]
在上游社区找到相关的补丁和讨论，但还没有发现官方发出的支持riscv64的版本
相关链接：[补丁](https://patchwork.kernel.org/project/linux-riscv/patch/20190416123233.4779-1-mick@ics.forth.gr/)
                  [含支持riscv64架构的版本](https://yhbt.net/lore/all/20210405085712.1953848-4-mick@ics.forth.gr/t/) ，但不清楚这是什么网站

**Comment by asdf1113** [comment]
用 含支持riscv64架构的版本的包 构建成功，但决定先研究是否能在不改变原压缩包的基础上增加补丁使其构建成功。

**Comment by laokz** [comment]
现已成功构建：https://build.tarsier-infra.com/package/show/openEuler:22.03/kexec-tools
