### ISSUE TITLE
[构建失败] httpd

### ISSUE THREAD

**Issue by asdf1113** [isrc-cas/tarsier-oerv#143]
[obs端构建日志](https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/httpd/standard_riscv64/riscv64)

错误信息：
`[ 1592s] gcc_old: fatal error: cannot read spec file '/usr/lib/rpm/openEuler/openEuler-hardened-ld': No such file or directory`

但在本地用 rpmbuild 构建成功
![image](https://user-images.githubusercontent.com/56477950/133990629-b3135d22-0038-43c2-b633-e3220edc2e3f.png)

[发现obs上有关宏的文件，提到了openEuler-hardened-ld](https://build.openeuler.org/package/view_file/home:roberto.sassu:branches:openEuler:20.03:LTS/openEuler-rpm-config/macros?expand=0)
感觉这个报错跟obs的配置或者与 gcc_old 有关，若是配置问题则可能有其他包有类似情况，不知道有没有人也遇到过这个问题，该如何解决？

**Comment by asdf1113** [comment]
nginx包也是一样的报错
https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/nginx/standard_riscv64/riscv64

**Comment by lazyparser** [comment]
已经修复
