### ISSUE TITLE
[构建失败] util-linux

### ISSUE THREAD

**Issue by xinminst** [isrc-cas/tarsier-oerv#145]
util-linux包没有built binaries记录，应该从来没有构建成功过，查看[util-linux构建失败日志](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/util-linux)的报错：
```
[ 6570s]          misc: flock: [04] exclusive                         ... FAILED (misc/flock-exclusive)
```
是测试里的一项失败了，查看service文件发现没有使用最新版本构建，换用src-openEuler里最新版本[obs构建](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/util-linux)是可以成功的，但是osc本地构建时依然是misc：flock这一项测试失败。后经过多次测试，发现构建时而成功时而失败，可能是属于反复迭代后编译产物会影响编译结果，但可能并不是简单地收敛到成功或失败，还需进一步分析。

**Comment by mc964203886** [comment]
我在这个仓库中构建成功，看看是否有参考价值，https://build.openeuler.org/package/show/home:mc:branches:openEuler:Mainline:RISC-V/utill-linux

**Comment by laokz** [comment]
现已稳定构建：https://build.tarsier-infra.com/package/show/openEuler:22.03/util-linux
