### ISSUE TITLE
[构建失败] automake

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#146]
在源码仓src-openEuler将automake fork到个人仓，在本地重新构建，构建成功，构建日志：[https://build.openeuler.org/build/home:jean9823:branches:openEuler:Mainline:RISC-V/openEuler_Mainline_RISC-V_standard_riscv64/riscv64/automake/_log](url)

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181228647-068bbfc7-0d21-49a9-96b2-9e8de9197568.png)
构建成功：https://build.tarsier-infra.com/package/show/Factory:RISC-V/automake
