### ISSUE TITLE
[构建失败]sscg

### ISSUE THREAD

**Issue by glutinous-rice-wine** [isrc-cas/tarsier-oerv#147]
错误原因是timeout
![image](https://user-images.githubusercontent.com/88713792/134176604-b056cd5e-1bfc-4f24-a97d-72ea538f773f.png)

**Comment by glutinous-rice-wine** [comment]
在spec文件中使用sed命令修改了meson.build文件
![image](https://user-images.githubusercontent.com/88713792/134191191-99412cbc-c5af-459d-a4ea-8590017a0c9c.png)
在个人仓库构建成功
![image](https://user-images.githubusercontent.com/88713792/134190907-92301f3c-caf5-47a4-bd9b-68a7cd48e50b.png)

**Comment by lazyparser** [comment]
good job

Hmm, sed 命令虽然可能有效，但是 直接修改数字 有点风险很大的样子，容易误伤。

比较合适的做法是

1. 把 timeout 的信息体现出来，sed 覆盖的范围更大一些
2. 给出一个 diff 的结果，看看哪些被修改了。

**Comment by glutinous-rice-wine** [comment]
本地构建也是超时的问题，在尝试编写一个patch去改正，由于本人的知识储备不足，还在学习相关的知识。

**Comment by laokz** [comment]
现已较稳定构建：https://build.tarsier-infra.com/package/show/openEuler:22.03/sscg
