### ISSUE TITLE
[构建失败]gnulib

### ISSUE THREAD

**Issue by YuanZheng612** [isrc-cas/tarsier-oerv#155]

**Comment by YuanZheng612** [comment]
这个是什么原因？spec文件的117line是一个修改日志！
[ 6974s] /var/run/obs/worker/3/build/build-recipe-spec: line 117: 1818520 Killed                  chroot $BUILD_ROOT su -c /.build.command - $BUILD_USER < /dev/null

**Comment by GeassCore** [comment]
长时间(3600s)没有输出，osb kill了编译过程，或者说在obs上这个编译卡住了

**Comment by xinminst** [comment]
本地osc build构建失败，报错信息：
![image](https://user-images.githubusercontent.com/87924498/139538181-f37f48f7-5f42-4d61-baf8-78f3cee7b85a.png)
而[个人在线构建](![image](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/gnulib)会卡住的地方本地也会卡住，卡了4个多小时。我看了一下大概是在导入Gnulib模块，应该是因为有很多依赖所以花了很长时间。个人在线构建应该是1个小时没有输出就会自动中止，但是在大工程中就没有中止，而是和本地osc构建是同样的报错。

**Comment by GeassCore** [comment]
看内容是java vm 创建要求allocate有点大，要么是java自身问题，那么参数问题
手动安装的java是java1.8 还是java 11

**Comment by xinminst** [comment]
我是osc build没有手动安装，看以前的issue说dnf按照spec编译依赖java-devel时默认下载高版本openjdk11，而gnulib编译需要依赖openjdk1.8

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181229339-a4a00ab6-2391-487a-a1b8-6bc5b6b460f8.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/gnulib
