### ISSUE TITLE
[构建失败]gspell

### ISSUE THREAD

**Issue by ShiHaoGao** [isrc-cas/tarsier-oerv#156]
构建gspell结果为unresolvable,显示问题：
[nothing provides gettext, nothing provides gobject-introspection-devel, nothing provides pkgconfig(enchant-2), nothing provides pkgconfig(glib-2.0) >= 2.44, nothing provides pkgconfig(gtk+-3.0) >= 3.20, nothing provides pkgconfig(iso-codes), nothing provides vala。]
再去库中查找gettext包，发现也是unresolvable，需要gcc-c++等包，但是依赖库中无gcc-c++，因此无法解决。

**Comment by laokz** [comment]
现已可以构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/gspell
