### ISSUE TITLE
[构建失败]gettext

### ISSUE THREAD

**Issue by ShiHaoGao** [isrc-cas/tarsier-oerv#157]
结果：unresolvable
原因：依赖gcc-c++,库中没有gcc-c++ entry

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181229463-7341cbe2-3a43-48d5-93cb-c61377886450.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/gettext
