### ISSUE TITLE
[构建失败]apr-util

### ISSUE THREAD

**Issue by glutinous-rice-wine** [isrc-cas/tarsier-oerv#159]
没能修改成功
观察错误原因是：

[ 2941s] gcc_old: fatal error: cannot read spec file '/usr/lib/rpm/openEuler/openEuler-hardened-ld': No such file or directory

obs在线构建是unresolvable
正在尝试本地构建

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181229612-89311323-3730-4248-aa23-d652aed12df2.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/apr-util
