### ISSUE TITLE
potential Security Issue of image V4

### ISSUE THREAD

**Issue by Xinlong-Wu** [isrc-cas/tarsier-oerv#163]
there is an wifi config called `CU_Yx1E` in 
> D1 openEuler 第四版镜像(docker)下载地址：https://mirror.iscas.ac.cn/plct/openEuler-D1-wifi-hdmi-docker-20210826.img.bz2

we can get the password of the connection.
it seems someone forget to delete when making image

![image](https://user-images.githubusercontent.com/43398706/135049916-efed5a0e-87e1-4e93-9cf3-ed49031fdea3.png)

**Comment by lazyparser** [comment]
感谢报告🎉

已经重置了该SSID的ID和密码。是人工进行镜像调试的时候的测试网络。2022年6月份之后已经完全自动化生成镜像了，并不会包含开发过程中的网络信息。

resolve/fixed
