### ISSUE TITLE
【构建失败】wxGTK3-devel

### ISSUE THREAD

**Issue by yxychristina** [isrc-cas/tarsier-oerv#164]
构建wxGTK3-devel结果为unresolvable,显示问题：
[nothing provides libc.so.6(GLIBC_2.32)(64bit)needed by SDL2]
是因为构建未能开始，依赖包丢失或者未被定义。库中查找wxGTK3-devel包，BuildRequires上说明需要的gcc-c++包，不在依赖库中，需要提前建立依赖包才可以进行修改

**Comment by yxychristina** [comment]
#149

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181230170-8634f125-baad-4940-b635-c11a87042060.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/wxGTK3
