### ISSUE TITLE
【构建失败】原因分析包括：yum-metadata-parser、rubygem-redcarpet、rubygem-bindex、squid、rubygem-unf_ext、scap-security-guide、rubygem-sqlite3

### ISSUE THREAD

**Issue by liujiawei929** [isrc-cas/tarsier-oerv#168]
[失败包的原因.pdf](https://github.com/plctlab/openEuler-riscv/files/7334756/yum-metadata-parser.pdf)

**Comment by liujiawei929** [comment]
还有的包失败原因报错为libecap-deevel架构不支持，猜测是源码中没有支持riscv架构。解决方法：1.原生社区添加支持（估计不现实2.添加patch支持ricv架构。例如squid。

**Comment by xijing21** [comment]
- [ ] yum-metadata-parser
- [ ] rubygem-redcarpet
- [ ] rubygem-bindex
- [ ] squid
- [ ] rubygem-unf_ext
- [ ] scap-security-guide
- [ ] rubygem-sqlite3

**Comment by xijing21** [comment]
https://build.tarsier-infra.com/package/show/openEuler:22.03/
中，除了squid 外，其它包都成功

**Comment by xijing21** [comment]
构建修复清单跟踪squid包，先关闭本issue
