### ISSUE TITLE
20211101  实习生外部可见交付物汇总表

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#178]
各位同学，11月1日观测点要到了。请准备好自己的「外部可见交付物」索引，提交到repo下的weeklyreports/monthly-report-10.md文档中。

文档内容将在PLCT开源进展月刊中公开，也是每位实习生贡献值的一个考核，请大家重视，并在10.30 下午5:00之前完成提交

**Comment by xinminst** [comment]
util-linux包：
- [issue](https://github.com/plctlab/openEuler-riscv/issues/145)
- [obs](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/util-linux)
- [PR](https://gitee.com/openeuler-risc-v/util-linux/pulls/1)

**Comment by Wenxiang233** [comment]
尝试构建emacs包
[obs](https://build.openeuler.org/package/live_build_log/home:ChengZou:branches:openEuler:Mainline:RISC-V/emacs/standard_riscv64/riscv64)
