### ISSUE TITLE
[构建失败] 原因分析包括：subversion、kata-containers、golang、libvpx、php-cli、libtcnative、openjdk-1.8.0、openwsman

### ISSUE THREAD

**Issue by asdf1113** [isrc-cas/tarsier-oerv#183]
subversion 和 kata-containers、golang
[subversion构建日志](https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/subversion/standard_riscv64/riscv64)
发现王老师个人仓下有构建成功的版本：[链接](https://build.openeuler.org/package/show/home:pandora/subversion) 但依赖仓不同。
[kata-containers](https://build.openeuler.org/package/show/home:LiShiYang:broken/kata-containers) 和 [golang](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/golang) 构建依赖subversion，可以等待 subversion 成功解决后验证这两个包

libvpx 和 php
libvpx 缺少 php-cli : [链接](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/libvpx)
提供 php-cli 的包 php 缺少nginx-filesystem, curl = 7.66.0-2.oe1 [链接](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/php)
解决 php 的依赖问题后在个人工程下构建失败：[链接](https://build.openeuler.org/package/live_build_log/home:LiShiYang:branches:openEuler:Mainline:RISC-V/php/standard_riscv64/riscv64)
关键原因：
`[ 3836s] /home/abuild/rpmbuild/BUILD/php-8.0.0/ext/pcre/pcre2lib/pcre2_jit_compile.c:82:2: error: #error Unsupported architecture
[ 3836s]    82 | #error Unsupported architecture`
[可参考的网站](https://github.com/php/php-src)

libtcnative 和 openjdk-1.8.0
[libtcnative](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/libtcnative) 为unresolvable
`nothing provides java-1.8.0-openjdk-headless needed by javapackages-tools`
[javapackages-tools](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/javapackages-tools) 构建成功
java-1.8.0-openjdk-headless 由 [openjdk-1.8.0](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/openjdk-1.8.0) 提供，但 openjdk-1.8.0 缺少 java-1.8.0-openjdk-devel，还未能找到合适的包加入依赖仓使其成功构建

[openwsman](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/openwsman)
缺少 libwsman，还未能找到合适的包加入依赖仓使其成功构建

**Comment by asdf1113** [comment]
openwsman 和 openjdk-1.8.0 都是缺少一定的包而无法构建，缺少的包又是它们本身提供的。解决方法为在外部找相应的rpm包，可以去上游社区直接下载rpm包或者源码包，或者自己本地构建生成rpm包。将相应的包加入自己个人工程的依赖仓下后使要解决的包成功构建，之后再将成功构建的包替换自己加入的包到依赖仓中。

**Comment by xijing21** [comment]
- [ ] subversion
- [ ] kata-containers
- [ ] golang
- [ ] libvpx
- [ ] php-cli
- [ ] libtcnative
- [ ] openjdk-1.8.0
- [ ] openwsman

**Comment by xijing21** [comment]
kata-containers在构建跟踪列表中继续跟踪修复
  php-cli找不到软件包和源代码仓库
  
  关闭本issue
