### ISSUE TITLE
[failed] subversion

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#192]
在添加docker功能的时候，发现相关包都卡在了subversion：
```
1. 添加docker

   版本：447f294a20834dac134ae7c2c70466d6de1be460

   nothing provides containerd, nothing provides docker-runc, nothing provides subversion needed by golang

   按照obs上的提示，依次添加对应的依赖包：

2. containerd

   nothing provides subversion needed by golang

3. runc

   nothing provides subversion needed by golang

4. golang

   nothing provides subversion needed by golang

5. subversion 
```

以上仅仅是一个docker包的依赖关系；还有很多其它的包也卡在subversion，因此需优先解决该包的问题。

**Comment by xijing21** [comment]
obs链接：https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/subversion
错误日志链接：https://build.openeuler.org/package/live_build_log/openEuler:Mainline:RISC-V/subversion/standard_riscv64/riscv64

**Comment by GeassCore** [comment]
https://build.openeuler.org/package/show/home:pandora/subversion
