### ISSUE TITLE
[构建失败]papi

### ISSUE THREAD

**Issue by mc964203886** [isrc-cas/tarsier-oerv#193]
构建报错：unresolvable                 

```            
nothing provides libkcapi-hmaccalc needed by dracut
```

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181230662-d1c46fad-44ee-4ac4-902a-e6d08e72243e.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/papi
