### ISSUE TITLE
修复 GCC

### ISSUE THREAD

**Issue by lazyparser** [isrc-cas/tarsier-oerv#203]
最新主线还没有构建成功。扫了一眼 log 看起来是 gmp 和 mpfr 没有。

**Comment by GeassCore** [comment]
同仓库branch,就ok
https://build.openeuler.org/project/show/home:pandora:toolchain本身无问题，glibc测试可能不稳定

**Comment by lazyparser** [comment]
https://build.openeuler.org/project/show/home:pandora:toolchain
看到
https://build.openeuler.org/package/show/home:pandora:toolchain/gcc

是 blocked。

看起啦 blocked by 

gmp-devel, mpfr-devel, glibc-devel, gmp, gmp-c++, mpfr, glibc-common

这些 oE/RV mainline 当真没有？

**Comment by lazyparser** [comment]
看这里是 succeed 了：

https://build.openeuler.org/project/monitor/home:zxs-un:openEuler:riscv64:BaseOS:stage1

**Comment by GeassCore** [comment]
blocked 只是由于mailine 的相关包在编译中或者blocked 看历史就好了
https://build.openeuler.org/package/binaries/home:pandora:toolchain/gcc/standard_riscv64
