### ISSUE TITLE
oE/RV 的QEMU镜像或其它镜像应当包含 man-db 包

### ISSUE THREAD

**Issue by lazyparser** [isrc-cas/tarsier-oerv#204]
也就是  `man cmd-name` 的基本用法是需要支持的。

**Comment by YunxiangLuo** [comment]
非常感谢您的建议！RISC-V openEuler 22.03 LTS 安装镜像目前已经预装了man-de。

**Comment by lazyparser** [comment]
感谢测试及确认！

resolve/fixed
