### ISSUE TITLE
[构建失败]gsl

### ISSUE THREAD

**Issue by mc964203886** [isrc-cas/tarsier-oerv#210]
构建报错：
```
[ 5488s] FAIL: test
[ 5488s] ==========
[ 5488s] 
[ 5488s] FAIL: mcholesky_invert unscaled hilbert (  4,  4)[0,2]: -2.55795384873636067e-13                        0
[ 5488s]  (-2.55795384873636067e-13 observed vs 0 expected) [789499]
```
针对riscv64架构进行了修改，
```
%ifarch aarch64 riscv64
export CFLAGS="$RPM_OPT_FLAGS -ffp-contract=off"
%endif
%configure
%{make_build}
```

本地构建成功正在申请pr

**Comment by mc964203886** [comment]
obs线上构建成功 https://build.openeuler.org/package/show/home:mc:branches:openEuler:Mainline:RISC-V/gsl

已提交pr https://gitee.com/openeuler-risc-v/gsl/pulls/1

**Comment by mc964203886** [comment]
本周obs环境变动再次导致gsl失败，但本地osc build 是成功的，等待环境稳定

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181231185-a60e0af6-08aa-466c-842e-1d3bb9013a12.png)
构建成功，关闭issue：https://build.tarsier-infra.com/package/show/openEuler:22.03/gsl
