### ISSUE TITLE
[构建失败]libseccomp

### ISSUE THREAD

**Issue by mc964203886** [isrc-cas/tarsier-oerv#213]
test未通过，
```

[ 6818s]  test type:  basic
[ 6818s] Test 52-basic-load%%001-00001 result:   FAILURE 52-basic-load rc=125

```
该test源码如下：
```
#include <errno.h>
#include <unistd.h>

#include <seccomp.h>

#include "util.h"

int main(int argc, char *argv[])
{
	int rc;
	struct util_options opts;
	scmp_filter_ctx ctx = NULL;

	rc = util_getopt(argc, argv, &opts);
	if (rc < 0)
		goto out;

	ctx = seccomp_init(SCMP_ACT_ALLOW);
	if (ctx == NULL)
		return ENOMEM;

	rc = seccomp_load(ctx);

out:
	seccomp_release(ctx);
	return (rc < 0 ? -rc : rc);
}
```
该用例用于测试seccomp-load函数的执行，成功时将返回0，失败时将返回一个负值
-ECANCELED 

系统故障

-EFAULT 

libseccomp内部故障

-EINVAL 

无效输入

-ENOMEM 
               
库无法分配足够的内存。 

-ESRCH 

由于线程问题无法加载过滤器。

参考 https://www.man7.org/linux/man-pages/man3/seccomp_load.3.html

目前返回值为125，无法与错误码匹配

**Comment by mc964203886** [comment]
已修复

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181231385-3fa32a8d-4aa4-4f80-bd39-3c63905a93bc.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/libseccomp
