### ISSUE TITLE
Monthly Sprint: 2021年12月31日前希望达到的目标

### ISSUE THREAD

**Issue by lazyparser** [isrc-cas/tarsier-oerv#215]
Last update 20211206

- [x] 完成对 2203 版本最小构建环境（BaseOS）的准备，确保所有的 pkg 的源代码来源于 gitee/src-openEuler(openEuler:2203:*) 或者 gitee/openEuler-risc-v 这两个群组下。
- [x] 在理解现有worker和构建环境前提下进行构建速度优化，将现有构建成功的2000+包的构建速度缩短到20小时。增加 riscv64 workers，必要时增加 OBS server 进行调度。
- [ ] 每日自动生成 ISO、QEMU qcow2、D1 Img、Unmatched Img 四种安装镜像（2203-daily）。
- [x] 通过软件所的镜像站提供 2203-daily 的更新源。
- [x] 继续修复软件包，确保安装镜像所需包的完整性，并新增500+新构建成功的包。

**Comment by xijing21** [comment]
QEMU qcow2、D1 Img、Unmatched Img 3种安装镜像已经具备，ISO还没有

**Comment by xijing21** [comment]
暂缓提供ISO镜像，等有RISCV PC再支持ISO格式
先关闭本issue
