### ISSUE TITLE
[构建失败]ocaml

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#218]
构建地址：https://build.openeuler.org/package/show/home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/ocaml
测试报错
![image](https://user-images.githubusercontent.com/89906695/145940400-4d74b73c-d5d8-4a5b-ad8a-3dd90ffa89c0.png)
![image](https://user-images.githubusercontent.com/89906695/145940941-3c725493-ed09-4a77-bdcc-63a0e2a411f7.png)
![image](https://user-images.githubusercontent.com/89906695/145940741-6bc8f10b-41ae-494d-91bb-b882c50d3ef6.png)
![image](https://user-images.githubusercontent.com/89906695/145940803-d79a209d-d565-4d2d-bfa4-13a161080142.png)

**Comment by lazyparser** [comment]
ocaml 属于编程语言包，可以去PLCT实验室问问 arch linux （archrv）小队的进展，去 arch 发行版抄一抄 （致敬）

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181232014-27f3e086-1b26-41a4-aee3-82abde8cbcb9.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/ocaml
