### ISSUE TITLE
源码仓中有文件夹但无法同步到obs问题

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#222]
目前obs无法同步源码仓中的文件夹，不知道是什么原因
例如openEuler-release这个包，源码地址
https://gitee.com/src-openeuler/openEuler-release
其中有一个文件夹generic-release-1.0
![image](https://user-images.githubusercontent.com/89906695/147719149-f4caa296-d3da-414f-a99f-4386560f8990.png)
但是这个文件夹无法同步到obs中
obs地址
https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/openEuler-release
![image](https://user-images.githubusercontent.com/89906695/147719401-7482f284-9a03-433f-a5fd-ae0cb91497b2.png)

目前发现这些包有类似问题
openEuler-release
openEuler-logos
openEuler-indexhtml
runc
containerd

**Comment by laokz** [comment]
遇到isula-build也是类似情况，将_service调整为x86样式的repo格式，就可以了，它能处理文件夹（好像使用的是obs的recompress服务）
```
    <service name="tar_scm_kernel_repo">
      <param name="scm">repo</param>
      <param name="url">next/openEuler/isula-build</param>
     </service>
```
