### ISSUE TITLE
[构建失败]libepoxy

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#225]
有一个测试项不过，感觉是llvm的问题
报错中有一句是说This target JIT is not designed for the host you are running，不知道是不是架构不支持
![image](https://user-images.githubusercontent.com/89906695/148156539-76aec5fb-0f07-4fbf-ba26-98a14c4bef1f.png)
构建日志在
https://build.openeuler.org/package/live_build_log/home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/libepoxy/standard_riscv64/riscv64
网上暂时没有找到有用的信息
哪位老师知道怎么处理吗

**Comment by luxufan** [comment]
真正的报错应该是在LLVM ERROR。关于JIT的应该只是警告

**Comment by luxufan** [comment]
能够提供fs131_variant0_partial 的函数源代码？

**Comment by fourdim** [comment]
fs131_variant0_partial 应该是 Fragment shader #131 variant #0
应该是由 mesa 生成的函数，出处未知

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181232141-03d7b171-d0f3-40fe-b145-502709dd26c5.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/libepoxy
