### ISSUE TITLE
[构建失败]oemaker

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#226]
这个包是openeuler自己的包
目前看好像只支持x86_64和aarch64，是否需要从我们riscv的obs上删除这个包？
源码仓地址：
https://gitee.com/openeuler/oemaker/

**Comment by GeassCore** [comment]
看上去是一定需要支持的包？不一定riscv上运行，但需要支持riscv构建

**Comment by xijing21** [comment]
openeuler社区开发的镜像生成工具，目前未支持riscv64镜像生成。
![image](https://user-images.githubusercontent.com/84754181/181232445-ee7e5b7f-a3be-4440-9124-0848de5b36c3.png)
