### ISSUE TITLE
[构建失败]perftest

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#229]
这个包报错如下
![image](https://user-images.githubusercontent.com/89906695/148727464-e4413dfa-19fb-47bc-980e-755e72cd818e.png)
查了下可能是不支持riscv
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=560264
github上有open的issue
https://github.com/linux-rdma/perftest/issues/49

**Comment by kuroro99** [comment]
看了一下主要问题是是perftest中获得当前时钟跳数的函数` get_cycles()`没有对riscv的支持，目前修改已经构建成功，在进行下一步测试以及准备向上游提交

**Comment by lvxiaoqian555** [comment]
太棒啦~~~

**Comment by lvxiaoqian555** [comment]
> 看了一下主要问题是是perftest中获得当前时钟跳数的函数` get_cycles()`没有对riscv的支持，目前修改已经构建成功，在进行下一步测试以及准备向上游提交

太棒啦

**Comment by lvxiaoqian555** [comment]
https://github.com/linux-rdma/perftest/pull/134
issue已经fix，close issue
