### ISSUE TITLE
[构建失败] perl-Pod-Checker

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#235]
未修改前，构建失败的原因是因为测试项t/pod/poderrs.t失败，obs上失败的log显示:
![image](https://user-images.githubusercontent.com/89007492/149688008-739c5af5-5286-4bcf-ae67-752fb531ba9f.png)

参考http://fedora.riscv.rocks/koji/buildinfo?buildID=186647 , 修改了spec文件
![image](https://user-images.githubusercontent.com/89007492/149688727-9b8c1ed6-1ca3-4540-a87f-a608bf8b73e9.png)

rebuild后，仍然显示t/pod/poderrs.t失败
![image](https://user-images.githubusercontent.com/89007492/149689012-e295cdb1-c023-492d-be4f-675e19b71d99.png)

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181232771-fe9d545b-efd0-4ea0-a0a2-348b8589b7b5.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/perl-Pod-Checker
