### ISSUE TITLE
[构建失败]mpich

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#238]
这个包修改spec以后报错
[ 3222s] checking whether Fortran 77 compiler accepts option -O2... no
[ 3224s] checking how to get verbose linking output from gfortran... configure: WARNING: compilation failed
[ 3224s] 
[ 3225s] checking for Fortran 77 libraries of gfortran... 
[ 3226s] checking whether gfortran accepts the FLIBS found by autoconf... no
[ 3226s] checking for valid entries in FLIBS... 
[ 3230s] checking whether gcc links with FLIBS found by autoconf... yes
[ 3237s] checking whether Fortran 77 and C objects are compatible... no
[ 3237s] checking for file... file
[ 3238s] configure: error: ****  Incompatible Fortran and C Object File Types!  ****
[ 3238s] F77 Object File Type produced by "gfortran  -fPIC -fallow-argument-mismatch -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection" is : : cannot open `' (No such file or directory).
[ 3238s]  C  Object File Type produced by "gcc  -O2 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection  -O2" is : : ELF 64-bit LSB relocatable, UCB RISC-V, version 1 (SYSV), with debug_info, not stripped.
[ 3241s] error: Bad exit status from /var/tmp/rpm-tmp.cjP3U7 (%build)
[ 3241s] 

这个是gfortran有问题嘛？还是配置有问题？
如报错所说不支持-O2，需要把-O2去掉吗（需要打patch）
各位老师有什么建议嘛
构建日志：
https://build.openeuler.org/build/home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/standard_riscv64/riscv64/mpich/_log

**Comment by misaka00251** [comment]
PR: https://gitee.com/openeuler-risc-v/mpich/pulls/3/files

**Comment by lazyparser** [comment]
good job.
