### ISSUE TITLE
[构建失败]openblas

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#240]
这个包目前在riscv上有测试项不过，使用最新官方源码也不通过
构建日志在
https://build.openeuler.org/package/live_build_log/home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/openblas/standard_riscv64/riscv64

fedora上面是将测试项注掉编译通过的
我们是否也将测试项注掉？

**Comment by laokz** [comment]
看起来这个版本对riscv64支持的还不是很好，出错的宏是由另外架构相关的宏控制的？
