### ISSUE TITLE
202201 请大家提交外部可见交付

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#241]
请大提交下自己的「外部可见交付物」索引

**Comment by mc964203886** [comment]
pr:     mariadb 
           
          

issues: 

            https://gitee.com/openeuler/RISC-V/issues/I4QUVP

           https://gitee.com/openeuler/RISC-V/issues/I4QIP4#note_8266049
          
           https://gitee.com/openeuler/RISC-V/issues/I4QA2S

          https://gitee.com/openeuler/RISC-V/issues/I4PB8T#note_8167667

          https://gitee.com/openeuler/RISC-V/issues/I4NMRJ

**Comment by zxs-un** [comment]
issue:
- [qrencode](https://gitee.com/src-openeuler/qrencode/issues/I4R5TD)
fix:
- [qrencode3](https://build.openeuler.org/package/show/home:zxs-un:openEuler:riscv64:22.03:qrencode-fc/qrencode3)
- [tss2](https://gitee.com/openeuler-risc-v/tss2/pulls/3)
test:
- [openssl](https://build.openeuler.org/package/show/home:zxs-un:openEuler:riscv64:22.03:tss2/openssl), success
- [runc](https://build.openeuler.org/package/show/home:zxs-un:openEuler:riscv64:22.03:tss2/runc), success
- [webkit2gtk3](https://build.openeuler.org/package/show/home:zxs-un:openEuler:riscv64:22.03:webkit2gtk3/webkit2gtk3), success
- [systemd](https://build.openeuler.org/package/show/home:zxs-un:openEuler:riscv64:22.03:webkit2gtk3/systemd), fail
mass build:
- [22.03:next](https://build.openeuler.org/project/monitor/home:zxs-un:openEuler:riscv64:22.03:next?utf8=%E2%9C%93&defaults=0&succeeded=1&arch_riscv64=1&repo_stage1_1a=1&repo_stage1_2a=1&lastbuild=1) use for build, success: 2284
doc:
- [build Fedora qemu-system-riscv64 image](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/img-build-fedora-riscv.md), tested and succeeded

**Comment by BigBrotherJu** [comment]
issues:

- [docker 测试](https://github.com/plctlab/openEuler-riscv/issues/232)
- [openjdk 测试](https://github.com/plctlab/openEuler-riscv/issues/233)
- [specjvm2008 benchmark 运行和结果记录](https://github.com/plctlab/openEuler-riscv/issues/236)
- [dacapo benchmark 运行和结果记录](https://github.com/plctlab/openEuler-riscv/issues/237)
- [renaissance suite benchmark 运行和结果记录](https://github.com/plctlab/openEuler-riscv/issues/242)

学习记录：

- [dnf 用法总结](https://gitee.com/jinjuhan/open-euler-notes/blob/main/dnf-notes.md)

**Comment by lvxiaoqian555** [comment]
issue：
[构建失败]libepoxy:https://github.com/plctlab/openEuler-riscv/issues/225
[构建失败]oemaker:https://github.com/plctlab/openEuler-riscv/issues/226
[构建失败]mozjs52:https://github.com/plctlab/openEuler-riscv/issues/227
[构建失败]perftest:https://github.com/plctlab/openEuler-riscv/issues/229
[构建失败]mpich:https://github.com/plctlab/openEuler-riscv/issues/238
[构建失败]bazel:https://github.com/plctlab/openEuler-riscv/issues/239
[构建失败]openblas:https://github.com/plctlab/openEuler-riscv/issues/240

pr：
python-xgboost:https://gitee.com/src-openeuler/python-xgboost/pulls/4
cfitsio:https://gitee.com/src-openeuler/cfitsio/pulls/4
jimtcl:https://gitee.com/src-openeuler/jimtcl/pulls/3
apr:https://gitee.com/src-openeuler/apr/pulls/20
rdma-core:https://gitee.com/src-openeuler/rdma-core/pulls/27
mstflint:https://gitee.com/src-openeuler/mstflint/pulls/17
subunit:https://gitee.com/src-openeuler/subunit/pulls/27
qt:https://gitee.com/src-openeuler/qt/pulls/32
gd:https://gitee.com/src-openeuler/gd/pulls/24
webkit2gtk3:https://gitee.com/src-openeuler/webkit2gtk3/pulls/40
compiler-rt:https://gitee.com/src-openeuler/compiler-rt/pulls/24
openssl:https://gitee.com/src-openeuler/openssl/pulls/72
ocaml:https://gitee.com/src-openeuler/ocaml/pulls/10
haproxy:https://gitee.com/src-openeuler/haproxy/pulls/44
augeas:https://gitee.com/src-openeuler/augeas/pulls/38
libffado:https://gitee.com/src-openeuler/libffado/pulls/5
grub2:https://gitee.com/src-openeuler/grub2/pulls/120
mutter:https://gitee.com/src-openeuler/mutter/pulls/17
libmodulemd:https://gitee.com/src-openeuler/libmodulemd/pulls/8
php:https://gitee.com/src-openeuler/php/pulls/77
systemd:https://gitee.com/src-openeuler/systemd/pulls/199
tracker:https://gitee.com/src-openeuler/tracker/pulls/5
postgresql:https://gitee.com/src-openeuler/postgresql/pulls/59

有分析结果的包：
gegl04	oscbuild成功，已收集rpm
proftpd	oscbuild成功，已收集rpm
webkit2gtk3	update reversion
breeze-icon-theme	remove _constraints
tog-pegasus	不支持riscv
libvma	不支持riscv
oemaker	不支持riscv
vdo	不支持riscv
oddjob	本地osc build 成功，已收集rpm
squid	依赖libecap，但libecap不支持riscv架构

python升级，仓库地址：
https://build.openeuler.org/project/show/home:lvxiaoqian:python3.8
https://build.openeuler.org/project/show/home:lvxiaoqian:python3.9
已收集fedora相关包作为依赖包发给俊强老师

**Comment by jiewu-plct** [comment]
向src-openEuler提交的pr:
etmem: https://gitee.com/src-openeuler/etmem/pulls/34
gsl: https://gitee.com/src-openeuler/gsl/pulls/6
libEMF: https://gitee.com/src-openeuler/libEMF/pulls/11
lxcfs-tools: https://gitee.com/src-openeuler/lxcfs-tools/pulls/32
papi: https://gitee.com/src-openeuler/papi/pulls/11
passenger: https://gitee.com/src-openeuler/passenger/pulls/8
perl-Sys-CPU: https://gitee.com/src-openeuler/perl-Sys-CPU/pulls/3
python-markdown: https://gitee.com/src-openeuler/python-markdown/pulls/15
python-tqdm: https://gitee.com/src-openeuler/python-tqdm/pulls/15
qt5-qtscript: https://gitee.com/src-openeuler/qt5-qtscript/pulls/8
syscontainer-tools: https://gitee.com/src-openeuler/syscontainer-tools/pulls/37
texlive-base: https://gitee.com/src-openeuler/texlive-base/pulls/24
virglrenderer: https://gitee.com/src-openeuler/virglrenderer/pulls/8

通过update revision构建成功之后直接在obs上submit package：
clevis
libseccomp
libyami
mariadb
perl-File-Find-Rule-Perl
perl-Pod-Usage
webkit2gtk3

issue:
custodia: https://github.com/plctlab/openEuler-riscv/issues/228
edk2: https://github.com/plctlab/openEuler-riscv/issues/221
perl-Pod-Checker: https://github.com/plctlab/openEuler-riscv/issues/235
python-mako: https://github.com/plctlab/openEuler-riscv/issues/230
mvapich2: https://github.com/plctlab/openEuler-riscv/issues/234
