### ISSUE TITLE
[构建失败] python-nose

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#248]
https://gitee.com/src-openeuler/python-nose/issues/I1S0N7
> python3 可以使用 python-nose2，建议清理

`src-openeuler` 已经关闭该仓库。

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181232847-cfecb96b-f7a8-4640-b5da-8332bfe14f72.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/python-nose
