### ISSUE TITLE
[构建失败] etcd

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#250]
# 已解决

## 测试报 `commits failed to converge!` 错误

`raft/rafttest/node_test.go` 中有 timeout 设置
```
if !waitCommitConverge(nodes, 100) {
```
RISC-V 性能问题，将其修改为更大的数值。

## 测试报 `expected took1 xxx < took2 xxx` 错误

RISC-V 性能问题，将其注释掉。

# 未解决

大量如下错误
```
panic: failed to open database
panic: cannot open database at /tmp/token-test190558301/member/snap/db (cannot allocate memory)
```

怀疑是内存不足的问题，待在本地编译测试。

**Comment by YukariChiba** [comment]
Update: 本地构建结果：在给虚拟机分配 8G 内存的情况下，上述内存不足问题依然存在，需要进一步的分析原因。

**Comment by GeassCore** [comment]
obs 如果是Mainline 分配了16G 如果是个人分配了 32G 并且都有 100G的swap

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181233109-4d846340-c836-46b4-9f94-af4386ff51f1.png)

构建成功，关闭issue：https://build.tarsier-infra.com/package/show/openEuler:22.03/etcd
