### ISSUE TITLE
[构建失败] attest-tools

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#256]
构建在生成文件列表阶段报错：

```
error: Path is outside buildroot: Cannot initialize libselinux
RPM build errors:
    Path is outside buildroot: Cannot initialize libselinux
```
搜索 `Cannot initialize libselinux` 可知在 `digest-list-tools` 的 `lib/selinux.c` 处：
```
h = selabel_open(SELABEL_CTX_FILE, NULL, 0);
if (!h) {
	pr_err("Cannot initialize libselinux\n");
	return -EPERM;
}
```
可知 `selinux` 初始化失败。
而 `getenforce` 显示为 `Disabled`，不应该有此问题。

同时查看 `rpm` 代码 `build/files.c`：
```
if (strncmp(diskPath, fl->buildRoot, fl->buildRootLen)) {
    rpmlog(RPMLOG_ERR, _("Path is outside buildroot: %s\n"), diskPath);
    goto exit;
}
```
似乎将一个并不在 buildRoot 中的文件添加到了软件包之中，目前尚未有头绪。

**Comment by GeassCore** [comment]
qemu cmd中 selinux好像是关闭的

**Comment by YukariChiba** [comment]
Update:
观察到其它构建成功的包存在如下日志：
```
 /usr/lib/rpm/brp-digest-list: line 32: gen_digest_lists: command not found
```
后发现 gen_digest_lists 是 openeuler 特有的 `digest-list-tools` 中的命令，而此问题似乎并不影响构建结果。

因此解决方案是在 `BuildRequires` 中去掉 `digest-list-tools-devel`。

**Comment by YukariChiba** [comment]
Update:
构建成功，此 issue 关闭。
