### ISSUE TITLE
是否有人将如下流程自动化？

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#260]
[pkgs_verinfo](https://docs.qq.com/sheet/DUGNPekJQY1RLQ3RG?tab=BB08J2)文档 需要定期维护，手动维护数据会导致更新频率低，最好是有自动化的方式去定期更新，提高数据实时性。

数据处理的流程如下：
https://github.com/isrc-cas/tarsier-oerv/tree/main/scripts/src-openEuler_VerInfo  工具帮助抓取软件包的各种信息，在此执行结果的基础上：
1. 列出工程中构建失败的包
    （1）通过对obs status 进行排序，过滤出failed状态的包
    （2）再继续按照has rpm history in * 排序，从未成功生成rpm的包、有历史rpm的包分开；
3. 对待修的包进行优先级排序（优先minios范围的包）
       然后跟minios按照包名进行关联，匹配出哪些失败的包在minios中，minios中的包优先级高；
5. 排除：排除已经在修、修复状态还未反馈到obs的包
       由于修包工作是持续性的事务，其状态需要一段时间后才能回溯到obs工程中，因此对于已经“在路上走”的包，为了避免重复修包，需要进行排除。这里排除的信息包括：
       （1）已经向中间仓提交PR的：已经提交了PR，但是PR未合并，或者合并后提交的obs submit未完成的，需要将已经提交PR的包排除
       （2）fork仓库，还未提交PR的：此信息目前难以自动化获取，手工维护的表格
       （3）处于预调阶段，还未fork仓库的：本部分可排除，也可不排除。由于目前待修包较多，因此采取排除策略。

**Comment by xijing21** [comment]
目前排序和排除，采用的excel的排序功能和vlookup函数实现的。每次pkgs_verinfo*表格更新后，都需要重新操作一次。
考虑是否有更自动，智能的方式去动态整理和维护【待修包列表】

**Comment by lazyparser** [comment]
已经完成/过时
