### ISSUE TITLE
[构建失败] fftw

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#264]
fftw 作为数学运算库，对精度和性能有很高的要求（

会报出：
```
Found relative error 4.527587e-34 (time shift)
```
这是测试过程中发现信号发生了时移。

经查找，`verify_r2r` 中的 `t_shift` 和 `verify_lib` 中的 `tf_shift` 均会有此错误产生，它们分别对应 `verify_r2r` 和 `verify_dft/rdft`。

最终，它们的精度容许值被 `tol` 控制，因此在 `bench_main.c` 中手动设置了较大的 `tol`。

但问题并未得到解决，会报出：
```
Found relative error xxxx (linear)
```
这是测试中发现信号线性变换中出现了误差。

但是值得注意的是，在 `advanced` repo 中该包构建是成功的，因此很难不怀疑可能是其它依赖包的问题。

**Comment by lazyparser** [comment]
nice catch
这种debugging属于 hard 难度。上吧，少年

**Comment by YukariChiba** [comment]
Update:
根据研究发现，`check.pl` 一旦开了 `nthreads` 就容易出现巨大的误差(甚至能到 e-00)，考虑通过 `--enable-thrads` 关闭此支持：
```
 if test "$enable_threads" = "yes" -o "$enable_openmp" = "yes"; then
  SMP_TRUE=
  SMP_FALSE='#'
else
  SMP_TRUE='#'
  SMP_FALSE=
fi
```

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181233444-60c5bc20-07e4-43d6-be34-cbd54cfbf6da.png)
构建成功，关闭：https://build.tarsier-infra.com/package/show/openEuler:22.03/fftw
