### ISSUE TITLE
确认下 oE上部分 PKG_CONFIG 缺失的问题？

### ISSUE THREAD

**Issue by lazyparser** [isrc-cas/tarsier-oerv#27]
今天的双周会上，王翔/俊强和吴伟都提及到了 PKG_CONFIG 的问题。

https://github.com/plctlab/openEuler-riscv/issues/26#issuecomment-906015035

我是本地源代码构建的时候提示没有，按照俊强的方法复制粘贴了环境变量之后依然没有解决问题。

之后merle？or？pandora提出来说oE目前的系统中即使安装了官方的rpm包也是没有的。

so,,, confused. 看起来是有bug/task要做。

**Comment by xijing21** [comment]
找到一种方法/一种脚本，能够批量的找出来 @jiewu-plct 

——————————————
该问题跟wangjunqiang 沟通后，其问题的本质是spec中%install或者%post脚本没有把*.pc放到相应目录，是spec install脚本不完整的问题。还需要单包去处理，不是很需要工具和脚本，因此该任务暂时忽略，后续如发现有类似工具需求，再新建issue。
