### ISSUE TITLE
[构建失败]bwa

### ISSUE THREAD

**Issue by lvxiaoqian555** [isrc-cas/tarsier-oerv#270]
由于sse不可用
riscv上没有`<emmintrin.h>`文件
参考
https://aws.amazon.com/cn/blogs/publicsector/generalized-approach-benchmarking-genomics-workloads-cloud-bwa-read-aligner-graviton2/
将 `<emmintrin.h>` 替换成 "sse2neon.h" 
报错
 sse2neon.h:123:10: fatal error: arm_neon.h: No such file or directory
这个文件应该是arm才有的，riscv上没有
构建地址
https://build.openeuler.org/package/show/home:lvxiaoqian:unresolvable/bwa

哪位老师有什么好的建议吗？

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181233709-9402c1c3-8bcc-4cee-ad1c-a9119ef6836a.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/bwa
关闭issue
