### ISSUE TITLE
[构建失败] aqute-bnd

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#294]
OBS: https://build.openeuler.org/package/show/home:Yukari:RISC-V:Fix:Standard/aqute-bnd

```
[ 2409s] [ERROR] /home/abuild/rpmbuild/BUILD/bnd-3.5.0.REL/biz.aQute.bndlib/src/aQute/bnd/testing/TestingLog.java:[221,16] cannot find symbol
[ 2409s] [ERROR]   symbol:   class Logger
[ 2409s] [ERROR]   location: class aQute.bnd.testing.TestingLog
```

Patch 0003 引入了 OSGI 7.0 支持，而构建环境中的 `osgi-compendium` 还是 6.0，缺少 `Logger` 类，且与现有 `osgi-core` 版本为 7.0 冲突，需要升级。

**Comment by YukariChiba** [comment]
现已编译成功： https://build.openeuler.org/package/show/home:Yukari:RISC-V:Fix:Dependency/aqute-bnd

**Comment by laokz** [comment]
那关闭了a
