### ISSUE TITLE
[构建失败] automake

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#298]
OBS: https://build.openeuler.org/package/show/home:Yukari:RISC-V:Fix:Standard/automake

尝试升级 automake 到 1.16.5，测试报错:
```
[ 4473s] FAIL: t/am-prog-cc-c-o.sh
[ 6394s] FAIL: t/ccnoco-lib.sh
[ 6399s] FAIL: t/ccnoco.sh
[54882s] # FAIL:  3
```
chroot 运行这些文件，发现 `configure` 时出现问题：
```
/usr/bin/ld: /lib64/lp64d/Scrt1.o: in function `.L0 ':
(.text+0x8): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
经查找发现执行 `gcc -v` 可复现问题，而 `gcc_old -v` 则无此问题。
在 chroot 外则无此问题，初步怀疑是 gcc 相关软件包版本出现问题。

**Comment by laokz** [comment]
gcc包安装了/usr/bin/cc，是到gcc的符号链接。automake测试时包装了一个脚本gcc，并将原gcc改为gcc_old，但没有改变cc的链接指向，造成测试脚本中gcc_old -v意图的cc -v，变成了gcc -v

**Comment by laokz** [comment]
这块说的不对了，x86也是这个情况。倒是gcc脚本开头的gcc_secure_exclude不一样

**Comment by laokz** [comment]
已经确认，问题出在工程配置%gcc_secure_exclude宏少"automake.spec"项
