### ISSUE TITLE
[构建失败] atlas

### ISSUE THREAD

**Issue by YukariChiba** [isrc-cas/tarsier-oerv#302]
OBS：https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/atlas

构建十分缓慢，按照 x4 的时间完全无法通过，且在本地环境卡在 60000s：
```
[64712s] BEGIN BASIC KERNEL TESTS:
[64712s]    Kernel sr1_C.c(900000) passes basic test
```

怀疑是 RISC-V 性能过于不足导致。

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181234035-0525d9f8-499f-4aed-8fef-1a6e9e9123fa.png)
构建成功：https://build.tarsier-infra.com/package/show/openEuler:22.03/atlas
