### ISSUE TITLE
wget出现 Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mollybuild** [isrc-cas/tarsier-oerv#56]
image版本：openEuler-D1-wifi-hdmi-docker-20210826.img.bz2
系统信息：
```
# uname -a
Linux openEuler-RISCV-rare 5.4.61 #20 SMP Thu Aug 26 11:50:01 CST 2021 riscv64 riscv64 riscv64 GNU/Linux
```

执行wget会报错，如下：
![78dfaa35a4979dca74c3d1f6f3ba7a3](https://user-images.githubusercontent.com/26591790/131967155-f5be45b7-5c68-4c1b-800f-6fa1eabe18df.png)

**Comment by xijing21** [comment]
![57f977738cde51f6f4a36e957f81896](https://user-images.githubusercontent.com/84754181/131968236-4ab39bba-fff2-4c76-9a5e-27443dc32042.png)

在ubuntu20.04上执行 wget https://mirror.iscas.ac.cn/plct/docker-riscv-bringups-v1.0.tar.gz 成功。

考虑是openEuler-D1-wifi-hdmi-docker-20210826.img.bz2 镜像上的wget可能存在问题，或者是回显有问题。

**Comment by xijing21** [comment]
@jiewu-plct   请协助在qemu上运行下这个镜像，执行wget是否能够复现上述问题
镜像：https://mirror.iscas.ac.cn/plct/openEuler-D1-wifi-hdmi-docker-20210826.img.bz2

**Comment by lvxiaoqian555** [comment]
![image](https://user-images.githubusercontent.com/89906695/132149242-b90e3429-f063-4afb-b171-796ce98e11de.png)
在D1/oE上执行wget https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/go1.17.linux-riscv64.tar.gz也遇到上述问题

**Comment by jiewu-plct** [comment]
> @jiewu-plct 请看是否能够复现上述问题
> 镜像：https://mirror.iscas.ac.cn/plct/openEuler-D1-wifi-hdmi-docker-20210826.img.bz2

验证结果：可以wget成功
```
[root@openEuler-RISCV-rare ~]# wget https://mirror.iscas.ac.cn/plct/docker-riscv-bringups-v1.0.tar.gz
--2021-09-06 01:38:50--  https://mirror.iscas.ac.cn/plct/docker-riscv-bringups-v1.0.tar.gz
Resolving mirror.iscas.ac.cn (mirror.iscas.ac.cn)... 124.16.138.121
Connecting to mirror.iscas.ac.cn (mirror.iscas.ac.cn)|124.16.138.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9827 (9.6K) [application/octet-stream]
Saving to: ‘docker-riscv-bringups-v1.0.tar.gz’

docker-riscv-bringu 100%[===================>]   9.60K  --.-KB/s    in 0.001s  

2021-09-06 01:38:51 (14.6 MB/s) - ‘docker-riscv-bringups-v1.0.tar.gz’ saved [9827/9827]

**Comment by mollybuild** [comment]
> > @jiewu-plct 请看是否能够复现上述问题
> > 镜像：https://mirror.iscas.ac.cn/plct/openEuler-D1-wifi-hdmi-docker-20210826.img.bz2
> 
> 验证结果：可以wget成功
> ![image](https://user-images.githubusercontent.com/89007492/132149427-97504194-d35e-4afd-a4ad-4ca714b7e240.png)

是用串口连的，还是ssh连的？

**Comment by jiewu-plct** [comment]
> > > @jiewu-plct 请看是否能够复现上述问题
> > > 镜像：https://mirror.iscas.ac.cn/plct/openEuler-D1-wifi-hdmi-docker-20210826.img.bz2
> > 
> > 
> > 验证结果：可以wget成功
> > ![image](https://user-images.githubusercontent.com/89007492/132149427-97504194-d35e-4afd-a4ad-4ca714b7e240.png)
> 
> 是用串口连的，还是ssh连的？

串口

**Comment by lvxiaoqian555** [comment]
我刚刚在串口也试了一下，wget成功，看来是ssh连接才有问题

**Comment by lazyparser** [comment]
已经超过三个月未有新的报告。关闭。如果有复现可以reopen
