### ISSUE TITLE
考虑是否可以创建一个slack群组作为自动化机器人的连接器来使用

### ISSUE THREAD

**Issue by lazyparser** [isrc-cas/tarsier-oerv#8]
Slack作为流程自动化和消息推送是完美的

**Comment by MarcaWitt** [comment]
@lazyparser  using slack is a goodndecision,slack can expand the range.

**Comment by MarcaWitt** [comment]
Whether to consider PLCT own the logo and website,put on the agenda. #25

**Comment by lazyparser** [comment]
slack一直没有用起来。后续也可能需要用开源软件工具进行替代。
