### ISSUE TITLE
[文档任务] 完成osc本地构建的文档

### ISSUE THREAD

**Issue by xijing21** [isrc-cas/tarsier-oerv#83]
针对https://github.com/plctlab/openEuler-riscv/issues/32 这个任务要做的内容，请整理完整的操作文档。
文档的目的：指导新人能够按照此文档完成环境搭建，还有本地osc的方式进行包的构建和问题分析工作的开展。

文档应该包含但不仅仅限于以下内容：
1. qemu+oe环境的搭建
2. osc的安装
3. osc包构建的具体操作（依赖仓的添加、依赖包的添加等）

**Comment by zxs-un** [comment]
[openEuler on QEMU riscv64](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/vm-qemu-openEuler-riscv64.md)
[osc on openEuler riscv64](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/build-osc-build-tools.md)

**Comment by mc964203886** [comment]
我接下来接手功能使用的内容

**Comment by zxs-un** [comment]
[使用 osc build 在本地构建 openEuler OBS 服务端的内容](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/build-osc-obs-service.md)

**Comment by mc964203886** [comment]
**本文参考：** 
[本地搭建osc环境](https://gitee.com/lvxiaoqian/memo/blob/master/%E6%9C%AC%E5%9C%B0%E6%90%AD%E5%BB%BAosc%E7%8E%AF%E5%A2%83.md)
[osc构建一个包](https://gitee.com/lvxiaoqian/memo/blob/master/osc%E6%9E%84%E5%BB%BA%E4%B8%80%E4%B8%AA%E5%8C%85.md)
在本地构建方面这两篇已经十分详细，除了少数内容添加，大体不变。
[obs官方指导手册](https://openbuildservice.org/help/manuals/obs-user-guide)

安装QEMU 5.0.0
--
1. 安装以下依赖包

```
sudo apt install \
         build-essential autoconf automake autotools-dev pkg-config \
         bc curl gawk git bison flex texinfo gperf libtool patchutils mingw-w64 \
         libmpc-dev libmpfr-dev libgmp-dev libexpat-dev libfdt-dev \
         zlib1g-dev libglib2.0-dev libpixman-1-dev libncurses5-dev libncursesw5-dev

```
2. 下载qemu-5.0.0

```
cd ~
mkdir cache
cd ~/cache
wget -c https://download.qemu.org/qemu-5.0.0.tar.xz
tar -xvf qemu-5.0.0.tar.xz
```
3. 安装

```
mkdir ~/path
mkdir ~/cache/qemu-5.0.0-build
cd ~/cache/qemu-5.0.0-build
../qemu-5.0.0/configure --target-list=riscv64-softmmu,riscv64-linux-user --prefix=/home/lazy/path
make -j $(nproc)
make install
```
(安装时可能会涉及管理员权限 $sudo make install)
4. 配置

```
echo 'export PATH=/home/lazy/path/bin:$PATH' >> ~/.bashrc
source ~/.bashrc

```
命令qemu-system-riscv64 --version能正确显示安装的QEMU版本则表示安装成功。

在qemu中启动oE/RV
--
1. 下载image<br>
https://repo.openeuler.org/openEuler-preview/RISC-V/Image
* fw_payload_oe.elf --利用openSBI将kernel-5.5的image作为payload所制作的用于QEMU启动的image
* openEuler-preview.riscv64.qcow2 --openEuler RISC-V移植版的rootfs镜像

2. 启动oE/RV<br>
这里以主机端口转发的方式实现网络功能
```
qemu-system-riscv64 \
  -nographic -machine virt \
  -smp 8 -m 2G \
  -kernel fw_payload_oe.elf \
  -drive file=openEuler-preview.riscv64.qcow2,format=qcow2,id=hd0 \
  -object rng-random,filename=/dev/urandom,id=rng0 \
  -device virtio-rng-device,rng=rng0 \
  -device virtio-blk-device,drive=hd0 \
  -device virtio-net-device,netdev=usernet \
  -netdev user,id=usernet,hostfwd=tcp::12055-:22 \
  -append 'root=/dev/vda1 rw console=ttyS0 systemd.default_timeout_start_sec=600 selinux=0 highres=off mem=4096M earlycon'
```
默认的登陆用户名/密码是：root/openEuler12#$； 进入系统之后，所有的操作与openEuler系统一致

3. 设置时间<br>
`date -s "2021-09-09 14:00:01"`<br>
时间务必正确设置，错误的时间会影响诸如https的TLS认证等过程。

4. 禁用某些开机启动服务
```
systemctl disable auditd
systemctl disable systemd-networkd-wait-online
```


5. 配置软件包源
```
cd /etc/yum.repos.d
vim oe-rv.repo
[base]
name=base
baseurl=https://isrc.iscas.ac.cn/mirror/openeuler-sig-riscv/oe-RISCV-repo/
enabled=1
gpgcheck=0

[everything]
name=everything
baseurl=https://repo.openeuler.org/openEuler-preview/RISC-V/everything/
enabled=1
gpgcheck=0
```

6. 添加用户euler并设置密码，osc

```
adduser -d /home/euler -s /bin/bash euler
passwd euler
sudo - euler
```

安装osc
--
```
yum update
yum install osc
```
安装osc build
--

```
wget https://download.opensuse.org/repositories/openSUSE:/Tools/Fedora_Rawhide/noarch/obs-build-20210902-373.4.noarch.rpm
rpm -ivh obs-build-20210902-373.4.noarch.rpm 
```
(该仓库的obs版本已更新至obs-build-20210902-373.7.noarch.rpm，下载时以实际情况为准)
提示依赖不满足<br>
![输入图片说明](https://images.gitee.com/uploads/images/2021/0910/095207_1da1ab3c_9664902.png "屏幕截图.png")<br>

通过yum可以安装以下两个包

```
yum install -y psmisc
yum install -y  perl-TimeDate
```
其他的包需要下载rpm然后安装，rpm包在http://fedora.riscv.rocks/koji/buildinfo?buildID=161563 可以找到<br>
其中perl-MD5需要使用以下版本，否则需要升级glibc，不推荐

```
wget https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/o/obs-build-mkbaselibs-20210120-367.1.2.fc35.noarch.rpm
rpm -ivh obs-build-mkbaselibs-20210120-367.1.2.fc35.noarch.rpm 
wget http://fedora.riscv.rocks/kojifiles/packages/perl-MD5/2.03/29.fc29/noarch/perl-MD5-2.03-29.fc29.noarch.rpm
rpm -ivh perl-MD5-2.03-29.fc29.noarch.rpm
```
安装bsdtar时，发现已经有了旧版本的包
`yum install bsdtar`
![输入图片说明](https://images.gitee.com/uploads/images/2021/0910/133950_6a8e71db_9664902.png "屏幕截图.png")<br>
这里需要打破依赖检查，增加--force参数以强制安装

```
wget http://fedora.riscv.rocks/kojifiles/packages/libarchive/3.4.3/1.fc33/riscv64/libarchive-3.4.3-1.fc33.riscv64.rpm
rpm -ivh --force libarchive-3.4.3-1.fc33.riscv64.rpm
```

删除已安装的版本<br>
`rpm -evh libarchive-3.4.1-2.oe1.riscv64`<br>
安装需要的依赖

```
wget http://fedora.riscv.rocks/kojifiles/packages/libarchive/3.4.3/1.fc33/riscv64/bsdtar-3.4.3-1.fc33.riscv64.rpm
rpm -ivh bsdtar-3.4.3-1.fc33.riscv64.rpm
rpm -ivh obs-build-20210902-373.4.noarch.rpm

```

1. branch一个包

这里以aalib为例

`osc branch openEuler:Mainline:RISC-V aalib`<br>
第一次使用，会提示输入用户名密码，这里填写OBS的用户名密码<br>
输入以后报401，是因为配置文件里面配的是apiurl=https://api.opensuse.org<br>
修改配置文件

```
vim ~/.config/osc/oscrc
apiurl = https://build.openeuler.org/
no_verify = 1
最后添加
[https://build.openeuler.org]
user=username
pass=password

```
再次branch成功
此时OBS上可以看到branch的包
![OBS_branch](https://images.gitee.com/uploads/images/2021/0909/162436_c685efa0_9664902.png "屏幕截图.png")

2. co _service到本地

```
osc co home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/aalib
```

进入home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/aalib目录可以看到_service文件<br>


3. 然后根据_service下载源码包、补丁和spec文件等

```
osc up -S

```
可以看到包已经下载到本地<br>
![输入图片说明](https://images.gitee.com/uploads/images/2021/0910/143101_aef4e47a_9664902.png "屏幕截图.png")<br>
重命名由service下载的文件，使其能被本地 osc build 正确识别<br>
```
rm -f _service;for file in `ls | grep -v .osc`;do new_file=${file##*:};mv $file $new_file;done
```

4. 构建

`osc build`<br>
可能会报缺少sudo<br>
![输入图片说明](https://images.gitee.com/uploads/images/2021/0913/095500_3795c75f_9664902.png "屏幕截图.png")<br>

```
su
yum install sudo

```
再次运行osc build可能遇到如下报错，将用户加入sudo的配置文件<br>
![输入图片说明](https://images.gitee.com/uploads/images/2021/0913/102054_72268b0c_9664902.png "屏幕截图.png")

```
visudo
euler    ALL=(ALL)       ALL

```

5.个人分支仓库的管理


修改源代码和spec文件并提交到自己拉取的仓库

```

$osc addremove *
$osc ci -m "update source and spec"

```

新增内容


```
$osc add Newtar
$osc ci -m "add tar"

```
删除工程下的包（用于获得openEuler:Mainline:RISC-V的配置信息）


```
$cd home:lvxiaoqian:branches:openEuler:Mainline:RISC-V
$osc rm aalib
$osc commit -m "del aalib"

```

在个人工程下新增软件包

```
$cd home:lvxiaoqian:branches:openEuler:Mainline:RISC-V
$mkdir New-package
$osc add New-package
$osc ci -m "add New-package"
```
本地删除包或工程

```
$rm -rf home:lvxiaoqian:branches:openEuler:Mainline:RISC-V/aalib
$rm -rf home:lvxiaoqian:branches:openEuler:Mainline:RISC-V

```

添加新的依赖存储库


```

osc meta prj --edit home:lvxiaoqian:branches:openEuler:Mainline:RISC-V

```

 搜索 repository元素。 例如，允许使用 包裹来自 devel:languages:python在一个 openSUSE Tumbleweed 项目，扩展 repository元素：
 
 ```

< repository  name = "standard_riscv64" > 
    < path  project = "openEuler:Mainline:RISC-V"  repository = "standard_riscv64" /> 
    < path  project = "openSUSE:Factory"  repository = "standard_riscv64" /> 
    < arch > riscv64 </ arch > 
</repository > 

```



仓库的顺序path元素被从上到下搜索。
如果在第一个中找不到包，会读取第二个存储库。 当找到第一个库中找到合适的包时，它会被安装并且继续构建。
所以多数情况，应在指定的标准存储库之前添加额外的存储库。

**Comment by xijing21** [comment]
可以补充下 自己如何添加外部依赖包，已经本地构建通过后，引入的外部包如何进行管理，如何让obs在线构建也能成功的流程和步骤。
