### ISSUE TITLE
[xfce] 部分网页无法正常显示

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#86]
如baidu, sina, 163

**Comment by GeassCore** [comment]
webkit2git3的问题，百度等可能无法访问，debain可能存在一样问题
sogou可以访问并且检索

**Comment by jiewu-plct** [comment]
我装的虚拟机里的debian的预设浏览器是firefox,可以正常访问Baidu
![image](https://user-images.githubusercontent.com/89007492/132189556-596c0724-e9c2-4559-a035-47ea07b3bf37.png)

![image](https://user-images.githubusercontent.com/89007492/132189310-ff80b3de-357a-4e2f-bd2b-2f1e6ad73809.png)
